# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5

    steps:
      - checkout

      - restore_cache:
          keys:
            - libsodiumso-{{ checksum ".circleci/deps/libsodium.tar.gz" }}

      - run: ls -al /usr/local/lib
      - run: ls -al .

      - run: .circleci/install_libsodium.sh

      - run: cp -Lr /usr/local/lib/libsodium.so libsodium-contents.so; sudo rm /usr/local/lib/libsodium.so; sudo mv libsodium-contents.so /usr/local/lib/libsodium

      - save_cache:
          key: libsodiumso-{{ checksum ".circleci/deps/libsodium.tar.gz" }}
          paths:
            - /usr/local/lib/libsodium.so

      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)

      - run: mix deps.get
      - run: mix test
      - run: mix credo
