version: 2
jobs:
  build:
    docker:
      - image: smaximov/elixir-libsodium:1.8.1-alpine
        environment:
          MIX_ENV: test

    steps:
      - checkout

      - run: mix do deps.get --only test, compile
      - run: mix test
      - run: mix credo
