# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5

    steps:
      - checkout

      - run: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.13.tar.gz
      - run: tar xf libsodium-1.0.13.tar.gz
      - run: cd libsodium-1.0.13
      - run: ./configure
      - run: sudo make && sudo make check
      - run: sudo make install
      - run: cd ../

      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)

      - run: mix deps.get
      - run: mix test
      - run: mix credo
